### PR TITLE
Fix the image query selector crash

### PR DESCRIPTION
**Pull request by svbutko**
Fixes [the issues described here](https://github.com/sachinchoolur/lg-video.js/issues/9)

### CODE REVIEW

**Comment by ilirius** [comment]
I suggest another way:


var videoTitle, firstImage;

if (this.core.s.dynamic) {
    videoTitle = this.core.s.dynamicEl[index].title;
} else {
    videoTitle = this.core.items[index].getAttribute('title');
    firstImage = this.core.items[index].querySelector('img');
}

**Comment by svbutko** [comment]
> I suggest another way:
> 
> var videoTitle, firstImage;
> 
> if (this.core.s.dynamic) {
> videoTitle = this.core.s.dynamicEl[index].title;
> } else {
> videoTitle = this.core.items[index].getAttribute('title');
> firstImage = this.core.items[index].querySelector('img');
> }

This way there's no guarantee that there won't be `querySelector` like it's now.
Later, things can change and the issue will come up again.

**Comment by svbutko** [comment]
@sachinchoolur, @sachinds ping.

**Comment by ilirius** [comment]
> > I suggest another way:
> > var videoTitle, firstImage;
> > if (this.core.s.dynamic) {
> > videoTitle = this.core.s.dynamicEl[index].title;
> > } else {
> > videoTitle = this.core.items[index].getAttribute('title');
> > firstImage = this.core.items[index].querySelector('img');
> > }
> 
> This way there's no guarantee that there won't be `querySelector` like it's now.
> Later, things can change and the issue will come up again.

This approach visually divides the logic of work with dynamic content and HTML elements.
In case of array of dynamic objects there's no need to even check for querySelector.

Perhaps @sachinchoolur has another view on this issue.

**Comment by sachinchoolur** [comment]
Thank you for the PR. And sorry for the delayed response :(

`firstImage` is required only in non-dynamic mode. I've made the changes -  https://github.com/sachinchoolur/lg-video.js/commit/28b2a90cb95d0edcced94b3086a096072add5b44

**Pull request merged**
